Add missing imports for sample config generation
Fix for the following 2 exceptions when generating the sample
configuration with "tox -egenconfig":

manila.share.drivers.ibm.gpfs.gpfs_share_opts,
AttributeError: 'module' object has no attribute 'ibm'

manila.share.drivers.zfssa.zfssashare.ZFSSA_OPTS,
AttributeError: 'module' object has no attribute 'zfssa'

Change-Id: I4985700997a81bf38b627bbc39193ef75a62667f