Fix concurrency issue in tempest test
Tempest test 'test_list_shares_with_detail_filter_by_extra_specs' fails
with following error from time to time:

ValueError: Share 'cdd499f7-6b02-4f47-8b39-7093b4d07e11' listed with
extra_specs filter has nonexistent share type 'share-type-1283899337'.

It happens because list of share types is taken for each step of a loop
Get list of share types only once and before taking list of shares, in
that case we will have share objects with still existing share types.

Change-Id: I0c29d16385255599b902757544e31ebbec79ca84
Closes-Bug: #1493125