Fix documentation build
manila/share/drivers/emc/plugins/registry.py was removed which leads to:

ImportError: No module named registry

while generating the documentation.

Change-Id: I3527e6bd37f56e5b1cbae0bdccd64487871ea560