Fix version number to Juno
We need to update the version number in setup.cfg, otherwise pbr will
fail with:
"error in setup command: Error parsing /opt/stack/new/manila/setup.cfg:
ValueError: git history requires a target version of
pbr.version.SemanticVersion(2014.2.0.0b4), but target version is
pbr.version.SemanticVersion(2013.2.0)"

Change-Id: I608c1dce0169fe78667e5818f2abff3dc8b11447