Fix pep8 F811 and F812
Fixes:
manila/scheduler/simple.py:74:45: F812 list comprehension redefines
  'service' from line 59
manila/api/v1/share_networks.py:147:41: F811 redefinition of unused
  'network' from line 29

Do not blacklist these tests anymore.

Partial-Bug: #1333290
Change-Id: Ibf3c170ada17a7af0708331331bc435942c3763b